dag_factory_query:
  default_args:
    owner: 'example_owner'
    start_date: 2022-03-07
    retries: 1
    retry_delay_sec: 300
  schedule_interval: '0 3 * * *'
  concurrency: 1
  max_active_runs: 1
  dagrun_timeout_sec: 60
  default_view: 'tree'  # or 'graph', 'duration', 'gantt', 'landing_times'
  orientation: 'LR'  # or 'TB', 'RL', 'BT'
  tasks:
    task_1:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: extract_from_db
      python_callable_file: /Users/imachado/Documentos/Desarrollo/Alkemy/OT234-python/airflow/plugins/DAGs_functions.py
    task_2:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: transform_extrated_data
      python_callable_file: /Users/imachado/Documentos/Desarrollo/Alkemy/OT234-python/airflow/plugins/DAGs_functions.py
      dependencies: [task_1]
    task_3:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: load_to_s3
      python_callable_file: /Users/imachado/Documentos/Desarrollo/Alkemy/OT234-python/airflow/plugins/DAGs_functions.py
      dependencies: [task_2]