dag_factory_univ:
  default_args:
    owner: 'airflow'
    start_date: 2022-06-18
    retries: 5
    retry_delay_minutes: 10
  schedule_interval: '0 3 * * *'
  concurrency: 1
  max_active_runs: 3
  tasks:
    extract:
      operator: airflow.operators.python_operator.PythonOperator
    transform:
      operator: airflow.operators.python_operator.PythonOperator
      dependencies: [extract]
    task_3:
      operator: airflow.operators.python_operator.PythonOperator
      dependencies: [transform]