dag_factory_univ:
  default_args:
    owner: 'airflow'
    start_date: 2022-06-18
    retries: 5
    retry_delay_minutes: 10
  schedule_interval: '0 3 * * *'
  concurrency: 1
  max_active_runs: 3
  tasks:
    extract:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: extract_from_db
      python_callable_file: plugins/DAGs_functions.py
    transform:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: transform_extrated_data
      python_callable_file: plugins/DAGs_functions.py
      dependencies: [extract]
    task_3:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: load_to_s3
      python_callable_file: plugins/DAGs_functions.py
      dependencies: [transform]